#!/usr/bin/php
<?php
/*
  vim: set expandtab tabstop=4 softtabstop=4 shiftwidth=4:
  Codificación: UTF-8
  +----------------------------------------------------------------------+
  | Issabel version 4.0                                                  |
  | http://www.issabel.org                                               |
  +----------------------------------------------------------------------+
  | Copyright (c) 2017 Issabel Foundation                                |
  +----------------------------------------------------------------------+
  | The contents of this file are subject to the General Public License  |
  | (GPL) Version 2 (the "License"); you may not use this file except in |
  | compliance with the License. You may obtain a copy of the License at |
  | http://www.opensource.org/licenses/gpl-license.php                   |
  |                                                                      |
  | Software distributed under the License is distributed on an "AS IS"  |
  | basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See  |
  | the License for the specific language governing rights and           |
  | limitations under the License.                                       |
  +----------------------------------------------------------------------+
*/

require_once 'Console/Getopt.php';
$cg = new Console_Getopt();
$allowedShortOptions = "d";
$args = $cg->readPHPArgv();
$ret = $cg->getopt($args, $allowedShortOptions);

if (PEAR::isError($ret)) {
    error_exit($ret->getMessage()."\n");
}

$opts = $ret[0];

$dahdi='';
if (sizeof($opts) > 0) {
    foreach ($opts as $o) {
        switch ($o[0]) { 
            case 'd':
               $dahdi=' -d ';
               break;
        }
    }
}

$file = $ret[1][0];

if($file=='') { echo "No file specified"; exit(1); }

passthru("/usr/sbin/issabel_migration.sh $dahdi -b $file");

function error_exit($sMsg, $errorcode = 1)
{
    fwrite(STDERR, $sMsg);
    exit($errorcode);
}
